### ISSUE TITLE
Why does it take 30 minutes for a model to generate text

### ISSUE THREAD

**Issue by Zhoues** [X-PLUG/mPLUG-Owl#125]
device: a A100-80G GPU
code:
![8](https://github.com/X-PLUG/mPLUG-Owl/assets/89010482/e019baa4-f98b-4796-a335-1343510e904c)
time:
![7](https://github.com/X-PLUG/mPLUG-Owl/assets/89010482/8d411fe9-97ac-4e58-aa70-15bf92ea5dab)

Are there good friends also confusing about this problem?

**Comment by FuxiaoLiu** [comment]
> device: a A100-80G GPU code: ![8](https://user-images.githubusercontent.com/89010482/259786242-e019baa4-f98b-4796-a335-1343510e904c.png) time: ![7](https://user-images.githubusercontent.com/89010482/259785938-8d411fe9-97ac-4e58-aa70-15bf92ea5dab.png)
> 
> Are there good friends also confusing about this problem?

I also confused about this at first. I edit the code a little bit ([link](https://github.com/FuxiaoLiu/LRV-Instruction/tree/main/utils)) so that we can run inference in batch more quickly.

**Comment by Zhoues** [comment]
> > device: a A100-80G GPU code: ![8](https://user-images.githubusercontent.com/89010482/259786242-e019baa4-f98b-4796-a335-1343510e904c.png) time: ![7](https://user-images.githubusercontent.com/89010482/259785938-8d411fe9-97ac-4e58-aa70-15bf92ea5dab.png)
> > Are there good friends also confusing about this problem?
> 
> I also confused about this at first. I edit the code a little bit ([link](https://github.com/FuxiaoLiu/LRV-Instruction/tree/main/utils)) so that we can run inference in batch more quickly.

Thank you very much!!
I have solved this question yesterday, so I closed this issue.
Anyway, thank you from the bottom of my heart!!

**Comment by srivivtcs** [comment]
Hi, could you please share the method you used to speedup the inference?

**Comment by Zhoues** [comment]
> Hi, could you please share the method you used to speedup the inference?

Hello，I am very glad to share my method with you.
The only thing you should do is to change the `Tokenizer`.

from:
```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(pretrained_ckpt)
```
to
```python
from transformers.models.llama.tokenization_llama import LlamaTokenizer
tokenizer = LlamaTokenizer.from_pretrained(pretrained_ckpt)
```
If this works for you, you can click on 👍

**Comment by srivivtcs** [comment]
Thanks, the suggested change is not giving any significant speedup in the inference. Is there anything else that I can try to speedup the inference?

**Comment by edchengg** [comment]
facing the same issue. the proposed fix is not working for me.

**Comment by Zhoues** [comment]
@srivivtcs @edchengg 
Hello! Because I do not have any detail about your problem, I would like to share my inference code, which only needs about 1 min to load model and 10s to generate text.

`model_worker.py`
```python
class mPLUG_Owl_Server:
    def __init__(
        self, 
        base_model='MAGAer13/mplug-owl-llama-7b',
        log_dir='./',
        load_in_8bit=False,
        bf16=True,
        device="cuda",
        io=None,
        use_lora=False,
        inference_mode=False,
        lora_r=8,
        lora_alpha=32,
        lora_dropout=0.05,
        delta_path='none',
    ):
        self.log_dir = log_dir
        self.image_processor = MplugOwlImageProcessor.from_pretrained(base_model)
        self.tokenizer = LlamaTokenizer.from_pretrained(base_model)
        self.processor = MplugOwlProcessor(self.image_processor, self.tokenizer)
        self.model = MplugOwlForConditionalGeneration.from_pretrained(
            base_model,
            load_in_8bit=load_in_8bit,
            torch_dtype=torch.bfloat16 if bf16 else torch.half,
            device_map="auto",
        )

        # LoRA part
        if use_lora:
            assert delta_path!='none', "If you use lora, please input lora path"
            # Load LoRA Config and Param
            peft_config = LoraConfig(
                target_modules=r'.*language_model.*\.(q_proj|v_proj)', 
                inference_mode=inference_mode, 
                r=lora_r, 
                lora_alpha=lora_alpha, 
                lora_dropout=lora_dropout
            )
            self.model = get_peft_model(self.model, peft_config)
            
            print('load lora from {}'.format(delta_path))
            prefix_state_dict = torch.load(delta_path, map_location='cpu')
            self.model.load_state_dict(prefix_state_dict, strict=False)

        self.tokenizer = self.processor.tokenizer
        self.bf16 = bf16
        self.load_in_8bit = load_in_8bit

        if not load_in_8bit:
            if bf16:
                self.model.bfloat16()
            else:
                self.model.half()
        self.model.eval()
        ......
```

`inference_2d.py` (I create)
```python
print(">> begin loading pretrained model")
t1 = datetime.datetime.now()
model = mPLUG_Owl_Server(
        base_model=args.pretrained_ckpt,
        load_in_8bit=not args.bf16,
        bf16=args.bf16,
        use_lora=args.use_lora,
        inference_mode=args.inference_mode,
        lora_r=args.lora_r,
        lora_alpha=args.lora_alpha,
        lora_dropout=args.lora_dropout,
        delta_path=args.delta_path,
    )
  t2 = datetime.datetime.now()
  print('load pretrained model time: ',t2 - t1)

  prompts = '''The following is a conversation between a curious human and AI assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.
  Human: <image>
  Human: ....
  AI: '''

  image_list =[...]

  data_format = {
      "text_input": prompts,
      "images": image_list if len(image_list) > 0 else [],
      "generation_config": {
      "top_k": int(3),
      "top_p": float(0.9),
      "num_beams": int(3),
      "no_repeat_ngram_size": int(2),
      "length_penalty": float(1.0),
      "do_sample": bool(True),
      "temperature": float(1.0),
      "max_new_tokens": 512,
      "early_stopping":bool(False)}}
  
   t3 = datetime.datetime.now()
  sentence = model.predict_parallel(data_format)
  t4 = datetime.datetime.now()
  print('Forward time: ',t4 - t3)

  print(sentence)

```

**Comment by edchengg** [comment]
Thanks a lot, Zhoues! Switching to worker_server is working well for me.

**Comment by srivivtcs** [comment]
@Zhoues, I am getting the following error while running the code snippet you shared. AttributeError: 'mPLUG_Owl_Server' object has no attribute 'predict_parallel'

**Comment by insafim** [comment]
Thank you @Zhoues for the solution. But for clarity I will share the codes in full.

**/mPLUG-Owl/mPLUG-Owl/serve/model_worker.py**

from PIL import Image
import torch
import gradio as gr
import logging
import sys
import os
import json
import requests
import datetime
import uuid
import base64
from io import BytesIO
import time
import sys
sys.path.append("..")

from .io_utils import IO, DefaultIO, OSS

import transformers
from mplug_owl.processing_mplug_owl import MplugOwlProcessor, MplugOwlImageProcessor
from mplug_owl.modeling_mplug_owl import MplugOwlForConditionalGeneration
from mplug_owl.configuration_mplug_owl import MplugOwlConfig
from transformers import GenerationConfig, AutoTokenizer, LlamaTokenizer

from .model_utils import post_process_output, Stream, Iteratorize

server_error_msg = "**NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.**"

# class mPLUG_Owl_Server:
#     def __init__(
#         self, 
#         base_model='MAGAer13/mplug-owl-llama-7b',
#         log_dir='./',
#         load_in_8bit=False,
#         bf16=True,
#         device="cuda",
#         io=None
#     ):
#         self.log_dir = log_dir
#         self.image_processor = MplugOwlImageProcessor.from_pretrained(base_model)
#         self.tokenizer = AutoTokenizer.from_pretrained(base_model)
#         self.processor = MplugOwlProcessor(self.image_processor, self.tokenizer)
#         self.model = MplugOwlForConditionalGeneration.from_pretrained(
#             base_model,
#             load_in_8bit=load_in_8bit,
#             torch_dtype=torch.bfloat16 if bf16 else torch.half,
#             device_map="auto"
#         )
#         self.tokenizer = self.processor.tokenizer
#         self.bf16 = bf16
#         self.load_in_8bit = load_in_8bit

#         if not load_in_8bit:
#             if bf16:
#                 self.model.bfloat16()
#             else:
#                 self.model.half()
#         self.model.eval()

class mPLUG_Owl_Server:
    def __init__(
        self, 
        base_model='MAGAer13/mplug-owl-llama-7b',
        log_dir='./',
        load_in_8bit=False,
        bf16=True,
        device="cuda",
        io=None,
        use_lora=False,
        inference_mode=False,
        lora_r=8,
        lora_alpha=32,
        lora_dropout=0.05,
        delta_path='none',
    ):
        self.log_dir = log_dir
        self.image_processor = MplugOwlImageProcessor.from_pretrained(base_model)
        self.tokenizer = LlamaTokenizer.from_pretrained(base_model)
        self.processor = MplugOwlProcessor(self.image_processor, self.tokenizer)
        self.model = MplugOwlForConditionalGeneration.from_pretrained(
            base_model,
            load_in_8bit=load_in_8bit,
            torch_dtype=torch.bfloat16 if bf16 else torch.half,
            device_map="auto",
        )

        # LoRA part
        if use_lora:
            assert delta_path!='none', "If you use lora, please input lora path"
            # Load LoRA Config and Param
            peft_config = LoraConfig(
                target_modules=r'.*language_model.*\.(q_proj|v_proj)', 
                inference_mode=inference_mode, 
                r=lora_r, 
                lora_alpha=lora_alpha, 
                lora_dropout=lora_dropout
            )
            self.model = get_peft_model(self.model, peft_config)
            
            print('load lora from {}'.format(delta_path))
            prefix_state_dict = torch.load(delta_path, map_location='cpu')
            self.model.load_state_dict(prefix_state_dict, strict=False)

        self.tokenizer = self.processor.tokenizer
        self.bf16 = bf16
        self.load_in_8bit = load_in_8bit

        if not load_in_8bit:
            if bf16:
                self.model.bfloat16()
            else:
                self.model.half()
        self.model.eval()
        self.io = io

    def evaluate(
        self, 
        pixel_values=None,
        input_ids=None,
        temperature=1.0,
        top_p=0.9,
        top_k=5,
        num_beams=3,
        max_new_tokens=256,
        stream_output=True,
        length_penalty=1.0,
        no_repeat_ngram_size=2,
        do_sample=False,
        early_stopping=True,
        **kwargs
    ):
        generation_config = dict(
            temperature=temperature,
            top_p=top_p,
            top_k=top_k,
            num_beams=num_beams,
            no_repeat_ngram_size=no_repeat_ngram_size,
            do_sample=do_sample,
            early_stopping=early_stopping,
            length_penalty=length_penalty,
        )
        
        generate_params = {
            "pixel_values": pixel_values,
            "input_ids": input_ids,
            "return_dict_in_generate": True,
            "output_scores": True,
            "max_new_tokens": max_new_tokens,
        }
        generate_params.update(generation_config)
        
        if stream_output:
            # Stream the reply 1 token at a time.
            # This is based on the trick of using 'stopping_criteria' to create an iterator,
            # from https://github.com/oobabooga/text-generation-webui/blob/ad37f396fc8bcbab90e11ecf17c56c97bfbd4a9c/modules/text_generation.py#L216-L243.

            def generate_with_callback(callback=None, **kwargs):
                kwargs.setdefault(
                    "stopping_criteria", transformers.StoppingCriteriaList()
                )
                kwargs["stopping_criteria"].append(Stream(callback_func=callback))
                with torch.no_grad():
                    self.model.generate(**kwargs)

            def generate_with_streaming(**kwargs):
                return Iteratorize(generate_with_callback, kwargs, callback=None)

            with generate_with_streaming(**generate_params) as generator:
                for output in generator:
                    # new_tokens = len(output) - len(input_ids[0])
                    decoded_output = self.tokenizer.decode(output)

                    if output[-1] in [self.tokenizer.eos_token_id]:
                        break

                    yield post_process_output(decoded_output)
            return  # early return for stream_output
        
        with torch.no_grad():
            generation_output = self.model.generate(
                pixel_values=pixel_values,
                input_ids=input_ids,
                return_dict_in_generate=True,
                output_scores=True,
                max_new_tokens=max_new_tokens,
                **generation_config
            )
        s = generation_output.sequences[0].cpu()
        output = self.tokenizer.decode(s)
        yield post_process_output(output)


    def predict_parallel(self, data):
        prompt = [data['text_input']]
        images = data['images'] if len(data['images']) > 0 else None
        
        if images:
            images = [Image.open(image) for image in images]
        inputs = self.processor(text=prompt, images=images, return_tensors='pt')
        input_ids = inputs['input_ids'].to(self.model.device)
        if 'pixel_values' in inputs:
            if self.load_in_8bit:
                pixel_values = inputs['pixel_values'].half().to(self.model.device)
            elif self.bf16:
                pixel_values = inputs['pixel_values'].bfloat16().to(self.model.device)
            else:
                pixel_values = inputs['pixel_values'].half().to(self.model.device)
        else:
            pixel_values = None
        
        with torch.no_grad():
            generation_output = self.model.generate(
                pixel_values=pixel_values,
                input_ids=input_ids,
                return_dict_in_generate=True,
                output_scores=True,
                **data['generation_config']
            )
        s = generation_output.sequences[0].cpu()
        output = self.tokenizer.decode(s)
        output = post_process_output(output)
        return output


**/mPLUG-Owl/mPLUG-Owl/infer_single_image_mlpugowl_fast.py**

import time
from serve.model_worker import mPLUG_Owl_Server

# Start timing for model initialization
start_time = time.time()

model = mPLUG_Owl_Server(
        base_model='MAGAer13/mplug-owl-llama-7b',
        load_in_8bit=False,
        bf16=True,
        use_lora=False,
        inference_mode=False,
        lora_r=8,
        lora_alpha=32,
        lora_dropout=0.05,
        delta_path='none',
    )

# End timing for model initialization
model_init_time = time.time() - start_time
print(f"Model initialization time: {model_init_time:.2f} seconds")

User_Prompt = 'Explain why this meme is funny.'
prompts = f'''The following is a conversation between a curious human and AI assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.
Human: <image>
Human: {User_Prompt}
AI: '''

# Start timing for image processing and input preparation
start_time = time.time()

image_list = ['./examples/rap.jpeg']

data_format = {
    "text_input": prompts,
    "images": image_list if len(image_list) > 0 else [],
    "generation_config": {
    "top_k": int(3),
    "top_p": float(0.9),
    "num_beams": int(3),
    "no_repeat_ngram_size": int(2),
    "length_penalty": float(1.0),
    "do_sample": bool(True),
    "temperature": float(1.0),
    "max_new_tokens": 512,
    "early_stopping":bool(False)}}

# End timing for image processing and input preparation
input_prep_time = time.time() - start_time
print(f"Input preparation time: {input_prep_time:.2f} seconds")


# Start timing for model inference
start_time = time.time()

sentence = model.predict_parallel(data_format)

# End timing for model inference
inference_time = time.time() - start_time
print(f"Model inference time: {inference_time:.2f} seconds")

print(sentence)
