### ISSUE TITLE
The environment installation is so confusing.

### ISSUE THREAD

**Issue by hongfangyu** [X-PLUG/mPLUG-Owl#21]
env.yaml depends on apex, and apex depends on the torch in env.yaml, it is not easy to install dependencies

**Comment by hongfangyu** [comment]
what is  "python-opencv==1.0.0.14" in env.yaml?

**Comment by MAGAer13** [comment]
Hi, sorry for your confusion. We will update the install instruction later. Some packages or requirements in env.yaml is redundant since we directly export it from our local environment for reference. 

For the minimum requirement, you only need to follow the package list [here](https://github.com/X-PLUG/mPLUG-Owl#install-requirements). 

Thank you for having interest in our work. If you have further questions about the installation, feel free to leave the comment below.

**Comment by MAGAer13** [comment]
> what is "python-opencv==1.0.0.14" in env.yaml?

This one is not required anymore.

**Comment by MAGAer13** [comment]
> env.yaml depends on apex, and apex depends on the torch in env.yaml, it is not easy to install dependencies

You can install the torch, torchvision with following command.
```python
conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia
```

Then, install the apex package with the instruction [https://github.com/X-PLUG/mPLUG-Owl#install-requirements](url)

**Comment by hongfangyu** [comment]
> > env.yaml depends on apex, and apex depends on the torch in env.yaml, it is not easy to install dependencies
> 
> You can install the torch, torchvision with following command.
> 
> ```python
> conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia
> ```
> 
> Then, install the apex package with the instruction [https://github.com/X-PLUG/mPLUG-Owl#install-requirements](url)

First I install the dependencies using env.yaml. And then there's an error of missing apex. After that, install apex manually. Finally install the dependencies using env.yaml again.

**Comment by MAGAer13** [comment]
Got it, let's just ignore the env.yaml file. Try to install the pytorch using the command first, then install apex with the instruction. Sorry for the confusion.
